server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: mqy

  # 数据库配置在application-local.yaml中配置

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

mybatis:
  configuration:
    # 数据库日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰命名映射
    map-underscore-to-camel-case: true

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

auth:
  token:
    token-name: token
    ttl: 3600000
    # secret-key请配置在application-local.yaml中